import { defaultSystemPrompt } from "./prompts";
import { sha256 } from "js-sha256";

export type ToolCallRequest = Record<string, {
  name: string;
  parameters: string;
}>

export type ToolCallResponse = Record<string, string>;

export type Interaction = {
  id: string;
  parentId: string | null;
  userMessage: string;
  agentMessage: string;
}

/**
 * Context is a context generated by agent via a single interation of LLM invocation.
 * @param interaction - The interaction that generated the context.
 */
export type Context = {
  interaction: Interaction;
  systemPrompt: string
  userMessage: string;
  parent: Context | null;
  summary: string;
  requests: ToolCallRequest;
}
